### PR TITLE
Added CI for Swift 6.0 and remove configs for older versions

### PR DESCRIPTION
**Pull request by akbashev**
Just want to be prepared for upcoming Swift 6 updates.

Basically copied https://github.com/yim-lee/swift-distributed-actors/tree/ci-5.10
But think on Jenkins side also should be updated...

### CODE REVIEW

**Comment by ktoso** [comment]
This will require asking @yim-lee for help to se tup the job.

**Comment by yim-lee** [comment]
@swift-server-bot test this please

**Comment by ktoso** [comment]
Seems like a real timeout perhaps

```

10:59:44 Test Suite 'SerializationTests' started at 2024-10-16 01:59:44.682
11:14:44 Test Case 'SerializationTests.test_deserialize_alreadyDeadActorRef_shouldDeserializeAsDeadLettBuild timed out (after 15 minutes). Marking the build as failed.
```

**Comment by ktoso** [comment]
Seems we're able to move over to github actions, either way that hang seems suspicious.

**Comment by akbashev** [comment]
@ktoso @yim-lee removed older versions also, as we don't need them anymore

**Comment by akbashev** [comment]
@ktoso @yim-lee with Swift 6 build time increases like several times, at least it shows 6 min for 5.10 and 25 min for 6.0. Is there a timeout set and can we maybe try to increase it? 🤔

**Comment by ktoso** [comment]
@swift-server-bot test this please

**Pull request merged**
