### PR TITLE
Add CI for Swift 5.8 and update nightly to Ubuntu 22.04

### PR DESCRIPTION
**Pull request by yim-lee**

### CODE REVIEW

**Comment by yim-lee** [comment]
@swift-server-bot test this please

**Comment by ktoso** [comment]
Those look like compiler crashes :|

**Comment by ktoso** [comment]
@swift-server-bot test this please

**Comment by ktoso** [comment]
@swift-server-bot test this please

**Comment by ktoso** [comment]
I merged so we can confirm this PR passes or not on 5.8, and then either way will merge and follow up any 5.8 issues.

https://github.com/apple/swift-distributed-actors/pull/1109

**Comment by ktoso** [comment]
@swift-server-bot test this please

**Comment by ktoso** [comment]
Hooray we don't have a 5.8 compiler regression after all then, that's good... I need to go, will double check shortly

**Comment by ktoso** [comment]
Hooray, 5.8 also good -- I was worried, I had some regressions reported but it seems we're good!

**Review by ktoso — APPROVED** [review]

**Comment by yim-lee** [comment]
🥳

**Pull request merged**
